### ISSUE TITLE
"About" layout with placeholders 

### ISSUE THREAD

**Issue by LeaHaelin** [palaviajeros/palaviajeros-ui#15]

**Comment by LeaHaelin** [comment]
- Page title: About us
- Image placeholder
- Text content with placeholder 


References
- https://barcelonalocalexperiences.com/about-us/
- https://atlantidaviatges.com/corporate/
- https://www.belocaltours.com/about-us-be-local-tours/
- https://weareworldexperience.com/about-us/
- https://interparktriple.com/
- https://company.ybtour.co.kr/
- https://www.modetour.com/

**Comment by jeandreidc** [comment]
We can use this page: https://company.ybtour.co.kr/ as a model
