### ISSUE TITLE
Research and finalize which component library we will be using

### ISSUE THREAD

**Issue by jeandreidc** [palaviajeros/palaviajeros-ui#5]
Task:

- [ ] Which are the design library options do we have?
- [ ] What are we using in the end, why?

**Comment by samchuu** [comment]
**Component Library Options** 
- Material UI, Chakra UI, Radix UI, Headless UI, Mantine

Ultimately went with Mantine because it provides more out-of-the-box components, built-in hooks and a modern look & feel.

https://mantine.dev/
