### ISSUE TITLE
Restyle get a quote form to handle flexible packages with no dates

### ISSUE THREAD

**Issue by jeandreidc** [palaviajeros/palaviajeros-ui#56]

**Comment by LeaHaelin** [comment]
isFlexible === true 
![Image](https://github.com/palaviajeros/palaviajeros-ui/assets/87936540/09ed91a8-460a-4109-8839-2b66f9086a26)
![Image](https://github.com/palaviajeros/palaviajeros-ui/assets/87936540/88b0b9ee-f869-4666-875f-3f91de6987ce)

isFlexible === false
![Image](https://github.com/palaviajeros/palaviajeros-ui/assets/87936540/fae43dbd-3e8c-4cd6-931a-50c7d5347389)



- [ ]  calculate the travel days from the json date
- [ ]  set the time zone UTC

**Comment by LeaHaelin** [comment]
- [ ] Change the checkbox name to "Choose Your Custom Date" 
- [ ] Add email validation for the travel dates(custom and fixed)
